FROM microsoft/dotnet AS base
WORKDIR /app


# copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

EXPOSE 80

# build runtime image
FROM microsoft/dotnet
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "tethys.server.dll"]