dist: trusty
sudo: false
language: node_js
notifications:
  email: false
cache:
  directories:
  - "./node_modules"
node_js:
- 8.11.1
before_install:
- npm install -g vuepress
install:
- npm install
script:
- npm run ci
deploy:
  provider: heroku
  api_key:
    secure: LfhEWrI6/AzzXQ1/M1uUvIlMzWsyQIcYLpCqWvCc5m2tgVTCwQbIhuSQXSemLLNN5CldQfIPc9eQaIVi1mwlw8MX+j9/D+1gTH2PKGC2MQwLD05Iol+j4IMxOVEo3/AE6b5ul/YTMji7+3XvnCApgsi6mWfAmn5tPgCucTJpsPR6XpTzJt9Pr28sPVem+7tg6B7sSAK0Ho4FNnqmY2SkSyN1a4AwrRat2U4DmOvpxbWuw0zoKAJO3ONACAzlUs/482fgmwMMDFhoZsNPgMaajRrzoZK4HKGSwztQPoHL2CoDNcEQaQQNOxfD2FSeMLaebnW1LFfVpnZGGNyET5VX9C9nQ3Nu9Wr97Z6NhLAXRBKnu/To/paNvC43eCkJ5vDB2FjXUVKxxM5fQwHm9w4sc6tDmDCJExJH5Q9PxqSYYf4n7NKdzl8j+zRsoANw9c7raPnFm5xJxtKlmIRer16ZlgIonYj3XdsrHK+FJPRXYk0Poi+pz+rr+w77dBkPzFa9T8Gv9S3KEMPV8rwRgXP7JJhAkCdJ5JRkpodbxrgwcn4drOl3we7gDBYT9m47uCi65jZ11e04GEdhvf0FZea8YhViQLuPPHLUZfLVOfRSPQvxaemmQOS3osW/IsMhj83+Raa5+zMfFhUSXbUWHLAT0ITnJj1U7W0qYdmWgbszd8A=
  skip_cleanup: true
  app: vue-starter
  on:
    repo: devCrossNet/vue-starter
